ARM: ixp4xx: fix compilation, add gpiolib support
The problem was introduced with commit:
"eb9ae7f gpio: fix build error in include/asm-generic/gpio.h"

This patch adds gpiolib support for the IXP4xx platform, which fixes the
compilation of several ixp4xx platforms, e.g.:

In file included from arch/arm/mach-ixp4xx/include/mach/gpio.h:72,
                 from /home/frogger/projects/server/linux/arch/arm/include/asm/gpio.h:9,
                 from include/linux/gpio.h:30,
                 from arch/arm/mach-ixp4xx/nslu2-setup.c:19:
include/asm-generic/gpio.h: In function 'gpio_get_value_cansleep':
include/asm-generic/gpio.h:218: error: implicit declaration of function '__gpio_get_value'
include/asm-generic/gpio.h: In function 'gpio_set_value_cansleep':
include/asm-generic/gpio.h:224: error: implicit declaration of function '__gpio_set_value'

Cc: Krzysztof Halasa <khc@pm.waw.pl>
Signed-off-by: Imre Kaloz <kaloz@openwrt.org>
[mkl: fix codingstyle; improve description]
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>